### ISSUE TITLE
Add imageLink/imageUrl to bookAdapters for createBook and updateBook

### ISSUE THREAD

**Issue by jpremo** [Code-the-Dream-School/bb-practicum-team1-front#102]
This can be done after BACK-80. Feel free to reassign if it makes more sense for @larasodjati to do this.

**Comment by Manizha-khorram** [comment]
> This can be done after BACK-80. Feel free to reassign if it makes more sense for @larasodjati to do this.

Thanks @jpremo, I will work on it.
