### ISSUE TITLE
Create a general modal component

### ISSUE THREAD

**Issue by jpremo** [Code-the-Dream-School/bb-practicum-team1-front#11]
I would recommend using the react-modal npm package for this. We want props to include id, className, and required (have to interact with modal to close it, can't simply click off it)

**Comment by Ekaterina-Bondareva** [comment]
I've checked documentation about react-modal (like this one [react-modal example](https://github.com/reactjs/react-modal/blob/master/README.md)). Could you please help to clarify the points bellow:

1. Is `id` prop will be used to set id of a new element inside modal or as an id of existing element on a page that should be shown inside modal?
2. If there are several elements inside modal will style be applied to every element or only to top level modal itself?
3. Are we going to use hardcoded buttons and pass click handlers as props or pass whatever contents of the modal as child elements?

**Comment by jpremo** [comment]
@Ekaterina-Bondareva id should be the id of the modal. Each modal will need a unique id. 

The hope is for the Modal component to be able to wrap around a dynamic set of children. In that way, you can really only plan for some general styling of the modal such as color, centering it on the page, background/overlay color, and maybe making it a flexbox. Let me know if you have other questions. Here's a general example of what the modal would look like in our code once implemented.

In writing this out I realized we will also need a boolean prop for whether the modal should be open/visible or not. That is also in the example below.

```
              <Modal open={false}>
                    <h1 className="modal-title">You've Been Logged Out</h1>
                    <div className="modal-text">
                        We look forward to seeing you again soon.
                    </div>
                    <div className="modal-button-box">
                        <div className="modal-link-div">
                            <div
                                className="modal-link modal-button"
                                onClick={cancel}
                            >
                                Close
                            </div>
                        </div>
                    </div>
                </Modal>
```
