### ISSUE TITLE
Add button to borrow/return book

### ISSUE THREAD

**Issue by Ekaterina-Bondareva** [Code-the-Dream-School/bb-practicum-team1-front#140]
A button should be added to BookItem/SingleBook component to mark book as borrowed or return borrowed book.

1) Only logged in user can see that button
2) Borrow button should appear only for book with "open" status
3) User cannot borrow its own books
4) Return back button should appear only for books with "borrowed" status
5) Return back button should be available only for book owner

**Comment by jpremo** [comment]
We have no concept of who has borrowed a book. I would recommend leaving this for the book owner to handle. As such a "mark as borrowed" and "mark as returned" button would only show up for books you own. It would probably be best to limit this to the profile page similar to the edit/delete buttons.

I do believe we actually can change borrowed status on the edit books page, so this ticket is a lower priority than we initially thought. It would still be nice to have a button for the operation though.
